### PR TITLE
Coalesce() fixes

### PR DESCRIPTION
**Pull request by stevereyes01**
Adding some coalesce() to fix some errors in uncoalesced segments

### CODE REVIEW

**Comment by lppekows** [comment]
Hi Steven,

this looks OK.  Possibly not optimal, but at this level I think we should be more concerned about correctness than performance.  Have you tried any test cases you could point me to?

**Comment by stevereyes01** [comment]
Oops. sorry I missed your message Larne, I haven't actually tested it, I was just basing it off of what Duncan told me the fix ought to be. Perhaps he has done some tests on it?

**Comment by duncan-brown** [comment]
This looks fine to me.

**Comment by lppekows** [comment]
It's probably fine, but I'd just like to see one short test to ensure things at the level of "objects on which coalesce are called really do support the method"

**Comment by duncan-brown** [comment]
@lenona tested this on segment files and we checked that the method does support it https://github.com/ligo-cbc/pycbc-glue/blob/master/glue/ligolw/utils/segments.py#L123

**Comment by lppekows** [comment]
Sounds good, thanks!  Pulled.

**Pull request merged**
